CREATE DATABASE MYDATABASE;

CREATE TABLE PART_TYPES
(
  PART_TYPE_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(300)
);

CREATE TABLE PROCESS_TYPES
(
  PROCESS_TYPE_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(200)
);

CREATE TABLE PRODUCT_TYPES
(
  PRODUCT_TYPE_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(300)
);

CREATE TABLE CUSTOMERS
(
  CUSTOMER_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  CUSTOMER_NAME VARCHAR(200),
  CUSTOMER_SURNAME VARCHAR(200),
  EMAIL VARCHAR(200) UNIQUE,
  ADDRESS VARCHAR(500),
  PHONE_NUMBER VARCHAR(100)
);

CREATE TABLE PARTS
(
  PART_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(300),
  PART_TYPE_ID INT(11),
  CONSTRAINT FK_PART_PARTYID FOREIGN KEY (PART_TYPE_ID) REFERENCES PART_TYPES (PART_TYPE_ID)
);

CREATE TABLE PRODUCTS
(
  PRODUCT_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(200),
  SERIAL_NUMBER VARCHAR(300),
  BRAND VARCHAR(200),
  MODEL VARCHAR(200),
  CUSTOMER_ID INT(11),
  PRODUCT_TYPE_ID INT(11),
  CONSTRAINT FK_PRODUCT_PRTYPE FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPES (PRODUCT_TYPE_ID),
  CONSTRAINT FK_PROD_CUST FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
);

CREATE TABLE PROCESSES
(
  PROCESS_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(300),
  PROCESS_DATE DATE,
  NEXT_PROCESS DATE,
  PRODUCT_ID INT(11),
  PROCESS_TYPE_ID INT(11),
  CHECKED TINYINT(1) DEFAULT 0,
  PART_ID INT(11),
  CONSTRAINT FK_PROCESSTYPE_PROCESS FOREIGN KEY (PROCESS_TYPE_ID) REFERENCES PROCESS_TYPES (PROCESS_TYPE_ID),
  CONSTRAINT FK_PROCESS_PART FOREIGN KEY (PART_ID) REFERENCES PARTS (PART_ID),
  CONSTRAINT FK_PRODUCT_PROCESS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
);

CREATE TABLE ROLES
(
  ROLE_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(200)
);

CREATE TABLE USERS
(
  USER_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  USER_NAME VARCHAR(200),
  USER_SURNAME VARCHAR(200),
  PASSWD VARCHAR(200),
  EMAIL VARCHAR(200) UNIQUE,
  PHONE_NUMBER VARCHAR(100),
  ROLE_ID INT(11),
  CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID)
);
CREATE INDEX FK_PROCESSTYPE_PROCESS ON PROCESSES (PROCESS_TYPE_ID);
CREATE INDEX FK_PROCESS_PART ON PROCESSES (PART_ID);
CREATE INDEX FK_PRODUCT_PROCESS ON PROCESSES (PRODUCT_ID);
CREATE INDEX FK_PRODUCT_PRTYPE ON PRODUCTS (PRODUCT_TYPE_ID);
CREATE INDEX FK_PROD_CUST ON PRODUCTS (CUSTOMER_ID);
CREATE INDEX FK_USER_ROLE ON USERS (ROLE_ID);
CREATE INDEX FK_PART_PARTYID ON PARTS (PART_TYPE_ID);

INSERT INTO PART_TYPES(DESCRIPTION) VALUES ('GPU');
INSERT INTO PROCESS_TYPES(DESCRIPTION) VALUES ('MAINTENANCE');
INSERT INTO PRODUCT_TYPES(DESCRIPTION) VALUES ('NOTEBOOK');
INSERT INTO CUSTOMERS(CUSTOMER_NAME,CUSTORMER_SURNAME,EMAIL,ADDRESS,PHONE_NUMBER) VALUES ('ALI YEKTAN','MUTLU','YEKTAN@OUTLOOK.COM','ÜSKÜDAR/İSTANBUL','0000000000');
INSERT INTO PARTS(DESCRIPTION,PART_TYPE_ID) VALUES ('MSI NVIDIA GTX1070',1);
INSERT INTO PRODUCTS(DESCRIPTION,SERIAL_NUMBER,BRAND,MODEL,CUSTOMER_ID,PRODUCT_TYPE_ID) VALUES ('GAMING NOTEBOOK','010203040506','MSI','GE70 APACHE',1,1);
INSERT INTO PROCESSES(DESCRIPTION,PROCESS_DATE,NEXT_PROCESS,PRODUCT_ID,PROCESS_TYPE_ID,CHECKED,PART_ID) VALUES ('BLABLABLA','2017-12-12','2017-12-19',1,1,0,1);
INSERT INTO ROLES(DESCRIPTION) VALUES ('ADMIN');
INSERT INTO USERS(USER_NAME,USER_SURNAME,PASSWD,EMAIL,PHONE_NUMBER,ROLE_ID) VALUES ('NAME','SURNAME','admin1234','user@gmail.com','00000000',1);